name = "VibrioNatriegens"
uuid = "77bc8a8b-a793-4fc4-98ef-9bd1d8b8270c"
authors = ["St. Elmo Wilken <stelmozors@gmail.com>"]
version = "0.1.0"

[deps]
AbstractFBCModels = "5a4f3dfa-1789-40f8-8221-69268c29937c"
COBREXA = "babc4406-5200-4a30-9033-bf5ae714c842"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
ReadableRegex = "cbbcb084-453d-4c4c-b292-e315607ba6a4"
RheaReactions = "e7041bdd-cbf6-4fda-a9ae-fa15d3238eb4"
SBMLFBCModels = "3e8f9d1a-ffc1-486d-82d6-6c7276635980"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
eQuilibrator = "9d196975-2c9b-462f-a3cc-8957d44b8c95"

[compat]
Conda = "1.10.2"
Measurements = "2.11.0"
PyCall = "1.96.4"
ReadableRegex = "0.3.2"
RheaReactions = "0.6.1"
SparseArrays = "1.11.0"
Unitful = "1.21.1"
eQuilibrator = "2.1.0"
