name = "VibrioNatriegens"
uuid = "77bc8a8b-a793-4fc4-98ef-9bd1d8b8270c"
version = "0.2.0"
authors = ["St. Elmo Wilken <stelmozors@gmail.com>"]

[deps]
AbstractFBCModels = "5a4f3dfa-1789-40f8-8221-69268c29937c"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
RheaReactions = "e7041bdd-cbf6-4fda-a9ae-fa15d3238eb4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ConstraintTrees = "1"
RheaReactions = "0.8.1"
SparseArrays = "1"

[extras]
COBREXA = "babc4406-5200-4a30-9033-bf5ae714c842"
ConstraintTrees = "5515826b-29c3-47a5-8849-8513ac836620"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ConstraintTrees", "HiGHS", "COBREXA"]
