name = "VibrioNatriegens"
uuid = "77bc8a8b-a793-4fc4-98ef-9bd1d8b8270c"
authors = ["St. Elmo Wilken <stelmozors@gmail.com>"]
version = "0.1.0"

[deps]
AbstractFBCModels = "5a4f3dfa-1789-40f8-8221-69268c29937c"
COBREXA = "babc4406-5200-4a30-9033-bf5ae714c842"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
ConstraintTrees = "5515826b-29c3-47a5-8849-8513ac836620"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONFBCModels = "475c1105-d6ed-49c1-9b32-c11adca6d3e8"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
ReadableRegex = "cbbcb084-453d-4c4c-b292-e315607ba6a4"
SBMLFBCModels = "3e8f9d1a-ffc1-486d-82d6-6c7276635980"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Timers = "21f18d07-b854-4dab-86f0-c15a3821819a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
eQuilibrator = "9d196975-2c9b-462f-a3cc-8957d44b8c95"

[compat]
Conda = "1.10.2"
FASTX = "2.1.7"
HiGHS = "1.12.1"
Measurements = "2.11.0"
PyCall = "1.96.4"
SparseArrays = "1.11.0"
Unitful = "1.21.1"
XLSX = "0.10.4"
eQuilibrator = "2.1.0"
