[deps]
BiGGReactions = "0f8c7381-4745-4de4-ab54-b92c670edbdd"
COBREXA = "babc4406-5200-4a30-9033-bf5ae714c842"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
Cleaner = "caabdcdb-0ab6-47cf-9f62-08858e44f38f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KEGGModuleParser = "8ec094ee-96fb-47c5-b407-8e5042c4c592"
MetaNetXReactions = "463f052f-59d6-49ce-a736-63fd8daf74b9"
RheaReactions = "e7041bdd-cbf6-4fda-a9ae-fa15d3238eb4"
Tulip = "6dd1b50a-3aae-11e9-10b5-ef983d2400fa"
