[deps]
COBREXA = "babc4406-5200-4a30-9033-bf5ae714c842"
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Tulip = "6dd1b50a-3aae-11e9-10b5-ef983d2400fa"
