[deps]
AbstractFBCModels = "5a4f3dfa-1789-40f8-8221-69268c29937c"
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
JSONFBCModels = "475c1105-d6ed-49c1-9b32-c11adca6d3e8"
SBMLFBCModels = "3e8f9d1a-ffc1-486d-82d6-6c7276635980"
